version: "3"
services:
  backend:
    build: ./backend
    ports:
    - ${HOST_PORT}:80
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - MODULE_NAME=backend.main
      - CONSOLE_LOGGING_LEVEL=${CONSOLE_LOGGING_LEVEL}
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
